version: '3'

services:
  apache2:
    build:
      context: ./.build
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "444:443"
    volumes:
      - ./lamp-docroot:/var/www/html
    #command: "a2enmod rewrite"
    #command: "service apache2 restart"
  mariadb:
    image: mariadb:10.7.4
    volumes:
      - ./lamp-docroot/tmp:/opt
      - ./lamp-mariadb-conf:/etc/mysql
      - ./db:/var/lib/mysql
#      - tf-mariadb-1:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db-1
      MARIADB_USER: docker
      MARIADB_PASSWORD: vnfw95htn9
    ports:
      - '3306:3306'
  redis:
#    container_name:redis${CONTNAME}
    image: redis
    ports:
      - "3379:3379"

